### ISSUE TITLE
https chrome error

### ISSUE THREAD

**Issue by caffeinum** [misterfresh/react-without-webpack#2]
![image](https://user-images.githubusercontent.com/1909384/48317452-9726e880-e603-11e8-9c37-eba6337984f5.png)

Yes, it's possible to tap "Ignore" everytime, but is there a way to make Chrome okay with this app?

**Comment by misterfresh** [comment]
This is because the certificate is self-signed. If you want to use a similar architecture on a live server, you can create a free certificate using Lets Encrypt.
Though normally that error is only on first load.
